### ISSUE TITLE
Ready to deploy Sample Distribution of OLS Estimators?

### ISSUE THREAD

**Issue by ethansaxenian** [ProfessorAmanda/econsimulations#141]
Is the Sample Distribution of OLS Estimators module ready to be deployed? Are there any additional features we want to add?

**Comment by ethansaxenian** [comment]
Any updates on this?

**Comment by tbyker** [comment]
Sorry. I did look and overall looks great. something is a little funny with axis and the normal plot in the standardize case. Let’s look at it together tomorrow. It is about how the y-axis is working.

T

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ethansaxenian** [comment]
Are you talking about the y-axis ticks? They are labeled as such because of the normal curve, unfortunately. I don't know if there's a way to change this.

**Comment by tbyker** [comment]
The problem is that what is on the y-axis is fundamentally different for the "histogram" than for the normal plot.  But we are forcing them to have the same units.  The y-axis for the normal plot is a probability and therefore ranges from 0 to 1.  But the dot graph showing the distribution of the sample has the count on the y-axis .  This will obviously range from zero to something well above 1.  At least I know (think!?) this is the case in the un-standardized version.  I am actually wondering what happens then to the y-axis.  Based on what I think we are doing to transition to the standard normal, I would have thought the y-axis would have the same range for the dots, but it doesn't seem to.   

Thinking about this lead me to look back to how we are dealing with this in CLT.  I think this is useful to do together because we should make sure labeling etc is consistent across modules.

**Comment by ethansaxenian** [comment]
Yeah, this is because the of the normal curve, which can't be scaled out of the 0 to 1 range. In order to overlay the points over the curve, I had to scale the points down to that range.

I am currently working on a fix for this, however!

**Comment by ethansaxenian** [comment]
I don't think this is an issue in CLT because we aren't plotting a bell curve.

**Comment by tbyker** [comment]
Yes, but the y-axis does something different when we go from regular to standardize in CLT aside from the bell curve (I think).  And also the axis is just labeled differently, so we can talk about making it consistent.


**********************************************
Tanya Byker

Associate Professor, Economics

Middlebury College
***@***.******@***.***>
**********************************************



________________________________

**Comment by ethansaxenian** [comment]
I see what you mean, the scale is a bit different... that's an easy fix. The axis appears to be labeled the same on my end, however. We'll discuss at 2:30

**Comment by tbyker** [comment]
Sounds good
