### ISSUE TITLE
Violate some assumptions

### ISSUE THREAD

**Issue by ethansaxenian** [ProfessorAmanda/econsimulations#173]
> Idea: what does it look like if we violate one of the assumptions?
→Take a non-random sample from the population. Eg. More likely to sample people in the treated group (bump up probability of sampling from that group). We will see that the estimator will converge to a value above the true value.
→ large outlier idea

**Comment by tbyker** [comment]
Feel free to tell me the following idea is dumb and/or too hard to implement:  Could we show the violation(s) as an animation?

eg.  We highlight the observations that are going to violate protocol in their pre-violation position and then click to show their new spot on the scatter.  Kind of like a "toggle" the problem on and off.  This would be in the initial "take samples" and "play with things" part of the module.  Then you just tell the user this is what is happening with each sample in the simulation.  I think it is powerful to see why the problem is occurring.  This idea could be for the failure to follow protocol and outlier example.  I think it is visually obvious what is going on with the non-random sample.


**********************************************
Tanya Byker

Associate Professor, Economics

Middlebury College
***@***.******@***.***>
**********************************************



________________________________
