### ISSUE TITLE
Getting Tanya to run things locally

### ISSUE THREAD

**Issue by tbyker** [ProfessorAmanda/econsimulations#286]
![image](https://user-images.githubusercontent.com/66968295/172852445-8ea87f79-b2fb-4279-a95b-63ae2f3af2e1.png)

**Comment by waynew99** [comment]
Good news! I have found this potential solution according to https://support.snyk.io/hc/en-us/articles/360002046418-JavaScript-heap-out-of-memory.

- Step1: 
- From the control panel go to System -> Advanced system settings -> Environment Variables -> New (user or system) and increase the Variable value as shown in the following screenshot:
![mceclip0](https://user-images.githubusercontent.com/49931122/172891766-98e26956-c6d7-408f-a5c4-237b5722f16f.png)

- Step2: 
- Open up the terminal. 
- (If the current directory is not `C:\Users\tbyker\Documents\econsimulations`, run `cd documents`, then `cd econsimulations`)
- Run `npm start`

Please let me know if it works.

**Comment by tbyker** [comment]
I tried the steps that Wayne sent and this seems to have worked:
![image](https://user-images.githubusercontent.com/66968295/172909426-e34d57d8-2756-456b-a0bc-866be3694ce6.png)
 
I can see the fixed effects module, but not the measurement error module: 
![image](https://user-images.githubusercontent.com/66968295/172909560-35d82356-7d07-482d-84f7-751ce83715eb.png)

**Comment by waynew99** [comment]
Great! I'm glad it worked. 
The reason that measurement error is not present is because it's on a different branch `measurementError`.
To view it, we need to switch to the `measrementError` branch:
1. Stop the server, by either closing the terminal, or by pressing `ctrl + c` in the running terminal.
2. In the same directory (if `C:\Users\tbyker\Documents\econsimulations` is not the current directory, run the two `cd` commands as before), run `git checkout measurementError`.
3. Run `npm start`.

**Comment by waynew99** [comment]
After migrating to NextJS, there are a few small changes regarding running locally. We can close this issue for now, and I can write up a short document describing the updated workflow.

**Comment by ProfessorAmanda** [comment]
Okay, sounds good!
