### ISSUE TITLE
Hypothesis Testing simulation with a two-sample test

### ISSUE THREAD

**Issue by ethansaxenian** [ProfessorAmanda/econsimulations#92]
How should the simulation change with a two sample test?

**Comment by ProfessorAmanda** [comment]
Hi Ethan,

Let me think about this. I can think of a few ways to go. I'm conflicted over whether to show the populations for the groups or to do everything in terms of the difference in means mu_1 - mu_2, which will be centered at zero.

**Comment by ProfessorAmanda** [comment]
Hi team,

Here's my idea for how to represent the simulation for the difference in means.

1. The left graph will show the populations observations for both populations, overlaid. It would be really excellent if we could color code the dots from each population. Note that the population graphs should be more or less overlapping, since under the null hypothesis, they have the same mean (the difference in means is zero; you can set them both to a mean of population 1), though they may have differing spreads (depending on how we set the parameters).
2. The right graph should show observations of the difference in sample means. This graph should be centered at 0. If the user has selected the option that they know the population standard deviations, you can overlay a normal curve based on the observations of the difference in sample means. If the user has selected that they do not know the pop. standard devs., you can just not overlay a curve for now.

What do you all think? Does this make sense?

**Comment by ethansaxenian** [comment]
Makes sense! I'll try this and see how it looks

**Comment by ethansaxenian** [comment]
What should the parameters be for these populations? In the one-sample test, the population has a mean of mu_0, which the user can adjust. But we don't have the same input for the two-sample test

**Comment by ethansaxenian** [comment]
So both populations are now displayed on the left (for now, both have mean 64 and sd 3) and the right graph is plotting the difference in means. However, I am getting the problem again where a one-tailed test is rejecting the null at both ends. Are the conditions to reject the null hypothesis different in a one-sample test and a two-sample test?

**Comment by ProfessorAmanda** [comment]
Can you remind me what parameters we are currently using for the two-sample test at the top of the page? I was thinking we could use the standard deviations we use at the top, the same mean for pop 1 as at the top, but have the mean of pop 2 be set equal to the mean of pop 1. I think that would embody the intuition of type I error best.

No, there is no difference in the conditions under which you reject, so you should not have a one-tailed test rejecting from both sides. Check the p-value calculation here (same way as with the one-sample tests).

**Comment by ethansaxenian** [comment]
It looks like we have a standard deviation of 3 for both populations (this should probably be changed?) and the mean is a random number between 61 and 66.

**Comment by ProfessorAmanda** [comment]
(Sorry I'm writing so many comments right now! I'm bored at my parents' house, lol)

Check the direction for rejection on the two-sample simulation. This is for the Ha: H_a: μ_1 - μ_2 < 0. The red dots should be on the left, since we reject for negative values of the test statistic.

<img width="361" alt="Screen Shot 2021-07-05 at 8 59 37 PM" src="https://user-images.githubusercontent.com/53241468/124527571-eed97a00-ddd3-11eb-9f85-fdc3df954e10.png">

**Comment by ethansaxenian** [comment]
Good catch! Looks like I had a typo in the code

**Comment by ethansaxenian** [comment]
Do you think we should randomize the standard deviation of the two populations as well? Perhaps in the range 1 <= SD <= 4?

**Comment by ProfessorAmanda** [comment]
That is a neat idea...I'll defer to you guys to decide!

**Comment by ethansaxenian** [comment]
@DavidGmidd what do you think about randomizing the standard deviations?
