### ISSUE TITLE
Triple-checking formulas HT

### ISSUE THREAD

**Issue by DavidGmidd** [ProfessorAmanda/econsimulations#93]
I have reviewed the formulas quite a few times, but the values seem a little odd. Another pair of eyes would help confirm that everything is correct.

**Comment by ProfessorAmanda** [comment]
Hi David,

I just looked at the work on the master branch. Is that the most recent version?

As far as I can tell, the test statistic for the two-sample test seems right, but it's hard to know, since I can't see the means. For sure, I think the p-value is not right. I just got a test statistic z = -.13 and a p-value of 0. The p-value should be relatively large for a test statistic that small in magnitude.

Amanda G. Gregg
Assistant Professor of Economics, Middlebury College
Join My Personal Zoom Room<https://middlebury.zoom.us/my/agregg?pwd=OWlGMmZMSWJaUkowRG5DUWJtRm9CQT09> (Password: EconHist)
Office: Farrell House 101
Office Phone: (802) 443 - 3419
Pronouns: she/her/hers

________________________________
From: DavidGmidd ***@***.***>
Sent: Friday, July 2, 2021 1:34 PM
To: ProfessorAmanda/econsimulations ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ProfessorAmanda/econsimulations] Triple-checking formulas HT (#93)


I have reviewed the formulas quite a few times, but the values seem a little odd. Another pair of eyes would help confirm that everything is correct.

**Comment by DavidGmidd** [comment]
Hi Amanda, yes, it is merged in master. 
I will re-visit the p-value. Thanks for checking!

**Comment by ethansaxenian** [comment]
@DavidGmidd is this issue still relevant?
